openapi: 3.2.0
info:
  title: M1Gateway - External Member Demographic API
  version: v1
security:
- basic: []
tags:
- name: MemberDemographic
paths:
  /ext/MemberDemographic/MemberId/{memberId}:
    get:
      tags:
      - MemberDemographic
      parameters:
      - in: path
        name: memberId
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items: {}
            application/json:
              schema:
                type: array
                items: {}
            text/json:
              schema:
                type: array
                items: {}
  /ext/MemberDemographic:
    patch:
      tags:
      - MemberDemographic
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Member_Demographic'
            application/json:
              schema:
                $ref: '#/components/schemas/Member_Demographic'
            text/json:
              schema:
                $ref: '#/components/schemas/Member_Demographic'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/MemberDemographicPatch'
          application/json:
            schema:
              $ref: '#/components/schemas/MemberDemographicPatch'
          text/json:
            schema:
              $ref: '#/components/schemas/MemberDemographicPatch'
          application/*+json:
            schema:
              $ref: '#/components/schemas/MemberDemographicPatch'
    post:
      tags:
      - MemberDemographic
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Member_Demographic'
            application/json:
              schema:
                $ref: '#/components/schemas/Member_Demographic'
            text/json:
              schema:
                $ref: '#/components/schemas/Member_Demographic'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Member_Demographic'
          application/json:
            schema:
              $ref: '#/components/schemas/Member_Demographic'
          text/json:
            schema:
              $ref: '#/components/schemas/Member_Demographic'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Member_Demographic'
    delete:
      tags:
      - MemberDemographic
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Member_Demographic'
            application/json:
              schema:
                $ref: '#/components/schemas/Member_Demographic'
            text/json:
              schema:
                $ref: '#/components/schemas/Member_Demographic'
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Member_Demographic'
          application/json:
            schema:
              $ref: '#/components/schemas/Member_Demographic'
          text/json:
            schema:
              $ref: '#/components/schemas/Member_Demographic'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Member_Demographic'
components:
  schemas:
    OperationType:
      format: int32
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      type: integer
    Member_DemographicOperation:
      type: object
      properties:
        operationType:
          $ref: '#/components/schemas/OperationType'
        path:
          type: string
        op:
          type: string
        from:
          type: string
        value: {}
    Member_Demographic:
      type: object
      properties:
        first_Inserted_By:
          type: string
        first_Inserted_Datetime:
          format: date-time
          type: string
        last_Changed_By:
          type: string
        last_Changed_Datetime:
          format: date-time
          type: string
        source_System_Id:
          format: int32
          type: integer
        source_Method_Id:
          format: int32
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        coreEntityStatusCode:
          type: string
        canEdit:
          type: string
        sourceSystemDisplayName:
          type: string
        isInternal:
          type: boolean
        returnField:
          type: boolean
        isPubSub:
          type: boolean
        id:
          format: int32
          type: integer
        member_Id:
          format: int32
          type: integer
        entered_By_Association_Id:
          format: int32
          type: integer
        category:
          type: string
        group_Code:
          type: string
        amount:
          format: double
          type: number
        comment:
          type: string
        recording_Date:
          format: date-time
          type: string
        note:
          type: string
        timestamp_Seq:
          format: int64
          type: integer
        owning_Poe_Id:
          format: int32
          type: integer
        enteredByAssociationName:
          type: string
    MemberDemographicPatch:
      type: object
      properties:
        member_Id:
          format: int32
          type: integer
        entered_By_Association_Id:
          format: int32
          type: integer
        category:
          type: string
        group_Code:
          type: string
        updates:
          $ref: '#/components/schemas/Member_DemographicJsonPatchDocument'
    IContractResolver:
      type: object
    Member_DemographicJsonPatchDocument:
      type: object
      properties:
        operations:
          type: array
          items:
            $ref: '#/components/schemas/Member_DemographicOperation'
          readOnly: true
        contractResolver:
          $ref: '#/components/schemas/IContractResolver'
  securitySchemes:
    basic:
      type: http
      scheme: basic
      description: Basic Authorization header using user and password
